// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact.post').default>>>>
    }
    '/api/private/cart/clear': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/private/cart/clear.delete').default>>>>
    }
    '/api/private/delete/cart': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/private/delete/cart.delete').default>>>>
    }
    '/api/private/get/cart': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/private/get/cart.get').default>>>>
    }
    '/api/private/put/cart': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/private/put/cart.put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_i18n/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}