// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/30/2025, 5:34:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/user/earthman-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/plugins/**/*.{js,ts,mjs}","/home/user/earthman-web/composables/**/*.{js,ts,mjs}","/home/user/earthman-web/utils/**/*.{js,ts,mjs}","/home/user/earthman-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/earthman-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;