// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/19/2025, 6:09:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/kai/Projekti/webshop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/plugins/**/*.{js,ts,mjs}","/home/kai/Projekti/webshop/composables/**/*.{js,ts,mjs}","/home/kai/Projekti/webshop/utils/**/*.{js,ts,mjs}","/home/kai/Projekti/webshop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kai/Projekti/webshop/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;