
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const AppFooter: typeof import("../components/AppFooter.vue")['default']
export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const AppNavigation: typeof import("../components/AppNavigation.vue")['default']
export const BackgroundVideo: typeof import("../components/BackgroundVideo.vue")['default']
export const CartPanel: typeof import("../components/CartPanel.vue")['default']
export const Carusel: typeof import("../components/Carusel.vue")['default']
export const CollectionHome: typeof import("../components/CollectionHome.vue")['default']
export const CollectionListing: typeof import("../components/CollectionListing.vue")['default']
export const CollectionShopListing: typeof import("../components/CollectionShopListing.vue")['default']
export const CookieControl: typeof import("../components/CookieControl.vue")['default']
export const Filter: typeof import("../components/Filter.vue")['default']
export const FilterPanel: typeof import("../components/FilterPanel.vue")['default']
export const HomePageListing: typeof import("../components/HomePageListing.vue")['default']
export const InstagramGrid: typeof import("../components/InstagramGrid.vue")['default']
export const MobileColorSlider: typeof import("../components/MobileColorSlider.vue")['default']
export const MobileMenu: typeof import("../components/MobileMenu.vue")['default']
export const Newsletter: typeof import("../components/Newsletter.vue")['default']
export const ProductAccordion: typeof import("../components/ProductAccordion.vue")['default']
export const ProductGallerySlider: typeof import("../components/ProductGallerySlider.vue")['default']
export const ShopListing: typeof import("../components/ShopListing.vue")['default']
export const ShopListingskeleton: typeof import("../components/ShopListingskeleton.vue")['default']
export const Toast: typeof import("../components/Toast.vue")['default']
export const Test: typeof import("../components/test.vue")['default']
export const TestCollectionListing: typeof import("../components/testCollectionListing.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const HeadlessCombobox: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']
export const HeadlessComboboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']
export const HeadlessComboboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']
export const HeadlessComboboxInput: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']
export const HeadlessComboboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']
export const HeadlessComboboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']
export const HeadlessDialog: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']
export const HeadlessDialogOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']
export const HeadlessDialogBackdrop: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']
export const HeadlessDialogPanel: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']
export const HeadlessDialogTitle: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']
export const HeadlessDialogDescription: typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']
export const HeadlessDisclosure: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']
export const HeadlessDisclosureButton: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']
export const HeadlessDisclosurePanel: typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']
export const HeadlessFocusTrap: typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']
export const HeadlessListbox: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']
export const HeadlessListboxLabel: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']
export const HeadlessListboxButton: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']
export const HeadlessListboxOptions: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']
export const HeadlessListboxOption: typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']
export const HeadlessMenu: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']
export const HeadlessMenuButton: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']
export const HeadlessMenuItems: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']
export const HeadlessMenuItem: typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']
export const HeadlessPopover: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']
export const HeadlessPopoverButton: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']
export const HeadlessPopoverOverlay: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']
export const HeadlessPopoverPanel: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']
export const HeadlessPopoverGroup: typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']
export const HeadlessPortal: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']
export const HeadlessPortalGroup: typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']
export const HeadlessRadioGroup: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']
export const HeadlessRadioGroupOption: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']
export const HeadlessRadioGroupLabel: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']
export const HeadlessRadioGroupDescription: typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']
export const HeadlessSwitchGroup: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']
export const HeadlessSwitch: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']
export const HeadlessSwitchLabel: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']
export const HeadlessSwitchDescription: typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']
export const HeadlessTabGroup: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']
export const HeadlessTabList: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']
export const HeadlessTab: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']
export const HeadlessTabPanels: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']
export const HeadlessTabPanel: typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']
export const HeadlessTransitionChild: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']
export const HeadlessTransitionRoot: typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyAppFooter: LazyComponent<typeof import("../components/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../components/AppHeader.vue")['default']>
export const LazyAppNavigation: LazyComponent<typeof import("../components/AppNavigation.vue")['default']>
export const LazyBackgroundVideo: LazyComponent<typeof import("../components/BackgroundVideo.vue")['default']>
export const LazyCartPanel: LazyComponent<typeof import("../components/CartPanel.vue")['default']>
export const LazyCarusel: LazyComponent<typeof import("../components/Carusel.vue")['default']>
export const LazyCollectionHome: LazyComponent<typeof import("../components/CollectionHome.vue")['default']>
export const LazyCollectionListing: LazyComponent<typeof import("../components/CollectionListing.vue")['default']>
export const LazyCollectionShopListing: LazyComponent<typeof import("../components/CollectionShopListing.vue")['default']>
export const LazyCookieControl: LazyComponent<typeof import("../components/CookieControl.vue")['default']>
export const LazyFilter: LazyComponent<typeof import("../components/Filter.vue")['default']>
export const LazyFilterPanel: LazyComponent<typeof import("../components/FilterPanel.vue")['default']>
export const LazyHomePageListing: LazyComponent<typeof import("../components/HomePageListing.vue")['default']>
export const LazyInstagramGrid: LazyComponent<typeof import("../components/InstagramGrid.vue")['default']>
export const LazyMobileColorSlider: LazyComponent<typeof import("../components/MobileColorSlider.vue")['default']>
export const LazyMobileMenu: LazyComponent<typeof import("../components/MobileMenu.vue")['default']>
export const LazyNewsletter: LazyComponent<typeof import("../components/Newsletter.vue")['default']>
export const LazyProductAccordion: LazyComponent<typeof import("../components/ProductAccordion.vue")['default']>
export const LazyProductGallerySlider: LazyComponent<typeof import("../components/ProductGallerySlider.vue")['default']>
export const LazyShopListing: LazyComponent<typeof import("../components/ShopListing.vue")['default']>
export const LazyShopListingskeleton: LazyComponent<typeof import("../components/ShopListingskeleton.vue")['default']>
export const LazyToast: LazyComponent<typeof import("../components/Toast.vue")['default']>
export const LazyTest: LazyComponent<typeof import("../components/test.vue")['default']>
export const LazyTestCollectionListing: LazyComponent<typeof import("../components/testCollectionListing.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyHeadlessCombobox: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['Combobox']>
export const LazyHeadlessComboboxLabel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxLabel']>
export const LazyHeadlessComboboxButton: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxButton']>
export const LazyHeadlessComboboxInput: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxInput']>
export const LazyHeadlessComboboxOptions: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOptions']>
export const LazyHeadlessComboboxOption: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/combobox/combobox")['ComboboxOption']>
export const LazyHeadlessDialog: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['Dialog']>
export const LazyHeadlessDialogOverlay: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogOverlay']>
export const LazyHeadlessDialogBackdrop: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogBackdrop']>
export const LazyHeadlessDialogPanel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogPanel']>
export const LazyHeadlessDialogTitle: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogTitle']>
export const LazyHeadlessDialogDescription: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/dialog/dialog")['DialogDescription']>
export const LazyHeadlessDisclosure: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['Disclosure']>
export const LazyHeadlessDisclosureButton: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosureButton']>
export const LazyHeadlessDisclosurePanel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/disclosure/disclosure")['DisclosurePanel']>
export const LazyHeadlessFocusTrap: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap")['FocusTrap']>
export const LazyHeadlessListbox: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['Listbox']>
export const LazyHeadlessListboxLabel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxLabel']>
export const LazyHeadlessListboxButton: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxButton']>
export const LazyHeadlessListboxOptions: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOptions']>
export const LazyHeadlessListboxOption: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/listbox/listbox")['ListboxOption']>
export const LazyHeadlessMenu: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['Menu']>
export const LazyHeadlessMenuButton: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuButton']>
export const LazyHeadlessMenuItems: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItems']>
export const LazyHeadlessMenuItem: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/menu/menu")['MenuItem']>
export const LazyHeadlessPopover: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['Popover']>
export const LazyHeadlessPopoverButton: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverButton']>
export const LazyHeadlessPopoverOverlay: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverOverlay']>
export const LazyHeadlessPopoverPanel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverPanel']>
export const LazyHeadlessPopoverGroup: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/popover/popover")['PopoverGroup']>
export const LazyHeadlessPortal: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['Portal']>
export const LazyHeadlessPortalGroup: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/portal/portal")['PortalGroup']>
export const LazyHeadlessRadioGroup: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroup']>
export const LazyHeadlessRadioGroupOption: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupOption']>
export const LazyHeadlessRadioGroupLabel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupLabel']>
export const LazyHeadlessRadioGroupDescription: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/radio-group/radio-group")['RadioGroupDescription']>
export const LazyHeadlessSwitchGroup: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchGroup']>
export const LazyHeadlessSwitch: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['Switch']>
export const LazyHeadlessSwitchLabel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchLabel']>
export const LazyHeadlessSwitchDescription: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/switch/switch")['SwitchDescription']>
export const LazyHeadlessTabGroup: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabGroup']>
export const LazyHeadlessTabList: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabList']>
export const LazyHeadlessTab: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['Tab']>
export const LazyHeadlessTabPanels: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanels']>
export const LazyHeadlessTabPanel: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/tabs/tabs")['TabPanel']>
export const LazyHeadlessTransitionChild: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionChild']>
export const LazyHeadlessTransitionRoot: LazyComponent<typeof import("../node_modules/@headlessui/vue/dist/components/transitions/transition")['TransitionRoot']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
